# Intro python data science
## Práctica 04: numpy ndarray

Vamos a ver cómo:
* Punto 1: Crear ndarrays en python
* Punto 2: Operar entre columnas
* Punto 3: Seleccionar elementos

# Punto 1:

In [1]:
# importar numpy
import numpy as np

In [2]:
# crear lista con numeros primos
numeros_primos=[2,3,5,7,11,13,17,19,23,29]
numeros_primos

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

In [3]:
# crear array a partir de lista
array_primos=np.array(numeros_primos)
array_primos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [4]:
# crear arrays con ceros o cómo inicializar un arreglo de numpy
array_zeros=np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# crear arrays con números
array_numeros=np.arange(10)
array_numeros

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# array con numeros pares
array_pares=np.arange(0,20,2)
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
# haciendo un reshape para dos dimensiones
A=array_pares.reshape(2,5)
A

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

# Punto 2:

In [10]:
# operaciones aritmeticas sobre np array 1-dimension y 2-dimension
array_impares=array_pares+1
array_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
# multiplicar por 100
array_impares*100

array([ 100,  300,  500,  700,  900, 1100, 1300, 1500, 1700, 1900])

In [12]:
# resta entre arrays
array_impares-array_pares

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
# cuidado con la división entre cero
array_pares/array_impares

array([0.        , 0.66666667, 0.8       , 0.85714286, 0.88888889,
       0.90909091, 0.92307692, 0.93333333, 0.94117647, 0.94736842])

In [14]:
# métodos asociados a estadística
# suma
array_primos.sum()

129

In [15]:
# promedio
array_primos.mean()

12.9

In [16]:
# varianza
array_primos.var()

73.28999999999999

In [18]:
# como ordenar un np array
array_fibonacci=np.array([0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233])

In [19]:
# orden ascendente: de menor a mayor
np.sort(array_fibonacci)

array([  0,   1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144,
       233])

In [22]:
# orden descendente: de mayor a menor
np.sort(-array_fibonacci)

array([-233, -144,  -89,  -55,  -34,  -21,  -13,   -8,   -5,   -3,   -2,
         -1,   -1,    0])

# Punto 3:

In [38]:
# Como seleccionar elements
print(A)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [ ]:
# Seleccionar un elemento

In [37]:
A[1,3]

16

In [ ]:
# seleccionar el primer elemento
A[1,3]

In [ ]:
# seleccionar algún otro elemento


In [ ]:
# Seleccionar varios elementos

In [48]:
# seleccionar por fila
A[:,2]

array([ 4, 14])

In [ ]:
# seleccionar por columna


In [ ]:
# Utilizar filter

In [49]:
array_fibonacci

array([  0,   1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144,
       233])

In [53]:
# conidicion para menores de 20
array_fibonacci<20

SyntaxError: invalid syntax (1204461938.py, line 2)

In [54]:
# filtrar menores de 20
array_fibonacci[array_fibonacci<20]

array([ 0,  1,  1,  2,  3,  5,  8, 13])

# Gracias!
## Espero que te lleves algo útil de este notebook 😀

Para más videos de programación para ciencia de datos

https://www.youtube.com/c/RafaGonzalezGouveia/

Si quieres realizar alguno de los cursos online de pago, ve a:

https://cursos.gonzalezgouveia.com